
CREATE TABLE IF NOT EXISTS mpa (
	mpa_id int8  GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	mpa_name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS films (
	film_id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	film_name varchar NOT NULL,
	description varchar NOT NULL,
	release_date timestamp NOT NULL,
	duration int8 NOT NULL,
	mpa_id int8 NOT NULL  REFERENCES mpa(mpa_id)
);

CREATE TABLE IF NOT EXISTS genre (
	genre_id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	genre_name varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS film_by_genre (
	film_id int8 NOT NULL REFERENCES films(film_id),
	genre_id int8  NOT NULL REFERENCES genre(genre_id),
	PRIMARY KEY (film_id, genre_id)
);



CREATE TABLE IF NOT EXISTS users (
	user_id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL  PRIMARY KEY,
	email varchar NOT NULL,
	login varchar NOT NULL,
	user_name varchar NOT NULL,
	birthday timestamp NOT NULL
);

CREATE TABLE IF NOT EXISTS likes (
	film_id int8 NOT NULL REFERENCES films(film_id),
	user_id int8 NOT NULL REFERENCES users(user_id),
	PRIMARY KEY (film_id, user_id)
);

CREATE TABLE  IF NOT EXISTS friend_status (
	status_id int8 GENERATED BY DEFAULT AS IDENTITY NOT NULL PRIMARY KEY,
	status varchar NOT NULL
);

CREATE TABLE IF NOT EXISTS friends (
	user_id int8 NOT NULL REFERENCES users(user_id),
	friend_id int8 NOT null REFERENCES users(user_id),
	status_id int8 NOT NULL REFERENCES friend_status(status_id),
	PRIMARY KEY (user_id, friend_id)
);





